// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription
import Foundation

let release = "test13"
let cdnBaseURL = "https://d1st2jzonb6gjl.cloudfront.net/vesper/\(release)/spm"

//autogenerated
let xcFrameworks: [(name: String, checksum: String)] = [
    ("AVDoris", "ed10fe555f82d6d374ec97dbf9f0d6e5299a386a3158f4ed418aad71abc6412b"),
    ("DzAVPlayerAdapter", "81d4e4924353b54366eaf685ffa9ad55404c84d1d816dacfb84fb273682ce2ad"),
    ("DzBase", "f2f25b7a3122926a3a3692913ba56cd0f746bd58a85d2e67473608395332afdb"),
    ("DzMediaTailorAdapter", "db534cb887e00a0d5deda1febe343e79e9195e3e59837a75fe65e2ecefd3ba94"),
    ("GoogleCast", "bcd6496e7529fc951875fc34afd403894fb6ff1826229d44ff5411493cfbc933"),
    ("MediaTailorSDK", "96831bc820a99e7bdbd57d17bae16cafa6473f7f4a804e18e0f482c4ca3813e0"),
    ("OMSDK_Elemental", "3cdeb3a76c9471cbeea2926c3c84b6cd84416db21dd375573759421a9886dc4e"),
    ("OMSDK_Yospace", "5226c4508ddc8479eeec841a3b16646d78d616578b8e2be6b99bf4b8b627a47b"),
    ("ProgrammaticAccessLibrary", "0912d86c0147c182b7b0aaa427cb7dd86d3916c8868799c21e9137b383c27e2e"),
    ("RxSwift", "0a39a22b58054d860080ba5a3c299e34df8cf0d99dc9f8f3de16102fc5466a30"),
    ("VesperPubNub", "5b11ad9b5b949b976331a2829ea9478dc85b236dd411e98053a8417dfe411ef3"),
    ("VesperSDK", "f94fa5ec1ee94234e00b5a88ce509ca58b30a256821bfcba4aa929560b7c783a"),
    ("YOAdManagement", "c1279b12b5ae89bc8f6eafc94b6cfd291ecda40563a626824c6c4c4b99983c85"),
    ("YOOpenMeasurementAdapter", "2a971b6d75465a6f555f30f7104b0af359c9bda7b9ef64d7283713f4bdf46ad1"),
    ("dice_shield_ios", "5f79ae6d8b9831d62bdf756c8aca3315e5912ccaf73400221a6119d769761d0b"),
] 

let remoteBinaryTargets: [Target] = xcFrameworks.map { target in
    return .binaryTarget(
        name: target.name,
        url: "\(cdnBaseURL)/iphoneFrameworks/\(target.name).xcframework.zip",
        checksum: target.checksum
    )
}

let localBinaryTargets: [Target] = xcFrameworks.map { target in
    .binaryTarget(
        name: target.name,
        path: "./iphoneFrameworks/\(target.name).xcframework"
    )
}

let privateTargetDependencies: [Target.Dependency] = xcFrameworks.map { Target.Dependency(stringLiteral: $0.name) }
let publicTargetDependencies: [Target.Dependency] = [
    .product(name: "MUXSDKStats", package: "mux-stats-sdk-avplayer"),
    .product(name: "GoogleInteractiveMediaAds", package: "swift-package-manager-google-interactive-media-ads-ios"),
    .product(name: "ConvivaAVFoundation", package: "conviva-ios-avfoundation-spm"),
]

let shouldUseLocalBinaryTargets = false
let binaryTargets = shouldUseLocalBinaryTargets ? localBinaryTargets : remoteBinaryTargets

let wrapperTarget: Target = .target(
    name: "VesperSDKWrapper",
    dependencies: privateTargetDependencies + publicTargetDependencies,
    resources: [.embedInCode("Resources")]
)

let packagePlatforms: [SupportedPlatform] = [.iOS(.v15)]
let packageProducts: [Product] = [.library(name: "VesperSDK", targets: ["VesperSDKWrapper"])]
let packageDependencies: [Package.Dependency] = [
    .package(url: "https://github.com/muxinc/mux-stats-sdk-avplayer", .upToNextMajor(from: "3.6.2")),
    .package(url: "https://github.com/googleads/swift-package-manager-google-interactive-media-ads-ios", .upToNextMajor(from: "3.22.0")),
    .package(url: "https://github.com/Conviva/conviva-ios-avfoundation-spm", .upToNextMinor(from: "4.0.51")),
]
let packageTargets = [wrapperTarget] + binaryTargets

let package = Package(
    name: "VesperSDK",
    platforms: packagePlatforms,
    products: packageProducts,
    dependencies: packageDependencies,
    targets: packageTargets
)

